name:                AdventOfCode2020
version:             0.1.0.0
github:              "lcycon/AdventOfCode2020"
license:             BSD3
author:              "Luke Cycon"
maintainer:          "luke@lukecycon"
copyright:           "2019 Luke Cycon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lcycon/AdventOfCode2020#readme>

ghc-options:
  - -Wall
  - -Werror

dependencies:
- base >= 4.7 && < 5
- advent-of-code-api
- dotenv
- text
- pretty-terminal
- parsec
- vector
- barbies
- refined
- unordered-containers

library:
  source-dirs: src

executables:
  AdventOfCode2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2020

tests:
  AdventOfCode2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2020
    - hspec
